unzip -l abel-v11-latin.zip > abel-v11-latin-temp.txt
unzip -l abhaya-libre-v5-latin.zip > abhaya-libre-v5-latin-temp.txt
unzip -l abril-fatface-v11-latin.zip > abril-fatface-v11-latin-temp.txt
unzip -l aclonica-v10-latin.zip > aclonica-v10-latin-temp.txt
unzip -l acme-v9-latin.zip > acme-v9-latin-temp.txt
unzip -l actor-v9-latin.zip > actor-v9-latin-temp.txt
unzip -l adamina-v13-latin.zip > adamina-v13-latin-temp.txt
unzip -l advent-pro-v10-latin.zip > advent-pro-v10-latin-temp.txt
unzip -l aguafina-script-v9-latin.zip > aguafina-script-v9-latin-temp.txt
unzip -l akronim-v10-latin.zip > akronim-v10-latin-temp.txt
unzip -l aladin-v9-latin.zip > aladin-v9-latin-temp.txt
unzip -l alata-v2-latin.zip > alata-v2-latin-temp.txt
unzip -l alatsi-v2-latin.zip > alatsi-v2-latin-temp.txt
unzip -l aldrich-v10-latin.zip > aldrich-v10-latin-temp.txt
unzip -l alef-v11-latin.zip > alef-v11-latin-temp.txt
unzip -l alegreya-sans-sc-v9-latin.zip > alegreya-sans-sc-v9-latin-temp.txt
unzip -l alegreya-sans-v10-latin.zip > alegreya-sans-v10-latin-temp.txt
unzip -l alegreya-sc-v11-latin.zip > alegreya-sc-v11-latin-temp.txt
unzip -l alegreya-v13-latin.zip > alegreya-v13-latin-temp.txt
unzip -l aleo-v3-latin.zip > aleo-v3-latin-temp.txt
unzip -l alex-brush-v11-latin.zip > alex-brush-v11-latin-temp.txt
unzip -l alfa-slab-one-v9-latin.zip > alfa-slab-one-v9-latin-temp.txt
unzip -l alice-v11-latin.zip > alice-v11-latin-temp.txt
unzip -l alike-angular-v11-latin.zip > alike-angular-v11-latin-temp.txt
unzip -l alike-v13-latin.zip > alike-v13-latin-temp.txt
unzip -l allan-v12-latin.zip > allan-v12-latin-temp.txt
unzip -l allerta-stencil-v10-latin.zip > allerta-stencil-v10-latin-temp.txt
unzip -l allerta-v10-latin.zip > allerta-v10-latin-temp.txt
unzip -l allura-v8-latin.zip > allura-v8-latin-temp.txt
unzip -l almendra-display-v11-latin.zip > almendra-display-v11-latin-temp.txt
unzip -l almendra-sc-v11-latin.zip > almendra-sc-v11-latin-temp.txt
unzip -l almendra-v13-latin.zip > almendra-v13-latin-temp.txt
unzip -l amarante-v8-latin.zip > amarante-v8-latin-temp.txt
unzip -l amaranth-v10-latin.zip > amaranth-v10-latin-temp.txt
unzip -l amatic-sc-v13-latin.zip > amatic-sc-v13-latin-temp.txt
unzip -l amethysta-v9-latin.zip > amethysta-v9-latin-temp.txt
unzip -l amiko-v5-latin.zip > amiko-v5-latin-temp.txt
unzip -l amiri-v14-latin.zip > amiri-v14-latin-temp.txt
unzip -l amita-v6-latin.zip > amita-v6-latin-temp.txt
unzip -l anaheim-v8-latin.zip > anaheim-v8-latin-temp.txt
unzip -l andada-v12-latin.zip > andada-v12-latin-temp.txt
unzip -l andika-v12-latin.zip > andika-v12-latin-temp.txt
unzip -l annie-use-your-telescope-v10-latin.zip > annie-use-your-telescope-v10-latin-temp.txt
unzip -l anonymous-pro-v13-latin.zip > anonymous-pro-v13-latin-temp.txt
unzip -l antic-didone-v9-latin.zip > antic-didone-v9-latin-temp.txt
unzip -l antic-slab-v8-latin.zip > antic-slab-v8-latin-temp.txt
unzip -l antic-v11-latin.zip > antic-v11-latin-temp.txt
unzip -l anton-v11-latin.zip > anton-v11-latin-temp.txt
unzip -l arapey-v8-latin.zip > arapey-v8-latin-temp.txt
unzip -l arbutus-slab-v8-latin.zip > arbutus-slab-v8-latin-temp.txt
unzip -l arbutus-v10-latin.zip > arbutus-v10-latin-temp.txt
unzip -l architects-daughter-v10-latin.zip > architects-daughter-v10-latin-temp.txt
unzip -l archivo-black-v9-latin.zip > archivo-black-v9-latin-temp.txt
unzip -l archivo-narrow-v11-latin.zip > archivo-narrow-v11-latin-temp.txt
unzip -l archivo-v6-latin.zip > archivo-v6-latin-temp.txt
unzip -l aref-ruqaa-v9-latin.zip > aref-ruqaa-v9-latin-temp.txt
unzip -l arima-madurai-v5-latin.zip > arima-madurai-v5-latin-temp.txt
unzip -l arimo-v13-latin.zip > arimo-v13-latin-temp.txt
unzip -l arizonia-v11-latin.zip > arizonia-v11-latin-temp.txt
unzip -l armata-v11-latin.zip > armata-v11-latin-temp.txt
unzip -l arsenal-v4-latin.zip > arsenal-v4-latin-temp.txt
unzip -l artifika-v11-latin.zip > artifika-v11-latin-temp.txt
unzip -l arvo-v13-latin.zip > arvo-v13-latin-temp.txt
unzip -l arya-v6-latin.zip > arya-v6-latin-temp.txt
unzip -l asap-condensed-v5-latin.zip > asap-condensed-v5-latin-temp.txt
unzip -l asap-v11-latin.zip > asap-v11-latin-temp.txt
unzip -l asar-v8-latin.zip > asar-v8-latin-temp.txt
unzip -l asset-v10-latin.zip > asset-v10-latin-temp.txt
unzip -l assistant-v4-latin.zip > assistant-v4-latin-temp.txt
unzip -l astloch-v12-latin.zip > astloch-v12-latin-temp.txt
unzip -l asul-v10-latin.zip > asul-v10-latin-temp.txt
unzip -l athiti-v5-latin.zip > athiti-v5-latin-temp.txt
unzip -l atma-v6-latin.zip > atma-v6-latin-temp.txt
unzip -l atomic-age-v13-latin.zip > atomic-age-v13-latin-temp.txt
unzip -l aubrey-v13-latin.zip > aubrey-v13-latin-temp.txt
unzip -l audiowide-v8-latin.zip > audiowide-v8-latin-temp.txt
unzip -l autour-one-v10-latin.zip > autour-one-v10-latin-temp.txt
unzip -l average-sans-v9-latin.zip > average-sans-v9-latin-temp.txt
unzip -l average-v9-latin.zip > average-v9-latin-temp.txt
unzip -l averia-gruesa-libre-v9-latin.zip > averia-gruesa-libre-v9-latin-temp.txt
unzip -l averia-libre-v9-latin.zip > averia-libre-v9-latin-temp.txt
unzip -l averia-sans-libre-v9-latin.zip > averia-sans-libre-v9-latin-temp.txt
unzip -l averia-serif-libre-v10-latin.zip > averia-serif-libre-v10-latin-temp.txt
unzip -l b612-mono-v5-latin.zip > b612-mono-v5-latin-temp.txt
unzip -l b612-v5-latin.zip > b612-v5-latin-temp.txt
unzip -l bad-script-v8-latin.zip > bad-script-v8-latin-temp.txt
unzip -l bahiana-v5-latin.zip > bahiana-v5-latin-temp.txt
unzip -l bahianita-v3-latin.zip > bahianita-v3-latin-temp.txt
unzip -l bai-jamjuree-v3-latin.zip > bai-jamjuree-v3-latin-temp.txt
unzip -l baloo-2-v1-latin.zip > baloo-2-v1-latin-temp.txt
unzip -l baloo-bhai-2-v1-latin.zip > baloo-bhai-2-v1-latin-temp.txt
unzip -l baloo-bhaina-2-v1-latin.zip > baloo-bhaina-2-v1-latin-temp.txt
unzip -l baloo-chettan-2-v1-latin.zip > baloo-chettan-2-v1-latin-temp.txt
unzip -l baloo-da-2-v1-latin.zip > baloo-da-2-v1-latin-temp.txt
unzip -l baloo-paaji-2-v1-latin.zip > baloo-paaji-2-v1-latin-temp.txt
unzip -l baloo-tamma-2-v1-latin.zip > baloo-tamma-2-v1-latin-temp.txt
unzip -l baloo-tammudu-2-v1-latin.zip > baloo-tammudu-2-v1-latin-temp.txt
unzip -l baloo-thambi-2-v1-latin.zip > baloo-thambi-2-v1-latin-temp.txt
unzip -l balsamiq-sans-v1-latin.zip > balsamiq-sans-v1-latin-temp.txt
unzip -l balthazar-v10-latin.zip > balthazar-v10-latin-temp.txt
unzip -l bangers-v12-latin.zip > bangers-v12-latin-temp.txt
unzip -l barlow-condensed-v4-latin.zip > barlow-condensed-v4-latin-temp.txt
unzip -l barlow-semi-condensed-v5-latin.zip > barlow-semi-condensed-v5-latin-temp.txt
unzip -l barlow-v4-latin.zip > barlow-v4-latin-temp.txt
unzip -l barriecito-v3-latin.zip > barriecito-v3-latin-temp.txt
unzip -l barrio-v5-latin.zip > barrio-v5-latin-temp.txt
unzip -l basic-v9-latin.zip > basic-v9-latin-temp.txt
unzip -l baskervville-v1-latin.zip > baskervville-v1-latin-temp.txt
unzip -l baumans-v10-latin.zip > baumans-v10-latin-temp.txt
unzip -l bebas-neue-v1-latin.zip > bebas-neue-v1-latin-temp.txt
unzip -l belgrano-v11-latin.zip > belgrano-v11-latin-temp.txt
unzip -l bellefair-v6-latin.zip > bellefair-v6-latin-temp.txt
unzip -l belleza-v9-latin.zip > belleza-v9-latin-temp.txt
unzip -l bellota-text-v2-latin.zip > bellota-text-v2-latin-temp.txt
unzip -l bellota-v2-latin.zip > bellota-v2-latin-temp.txt
unzip -l benchnine-v8-latin.zip > benchnine-v8-latin-temp.txt
unzip -l bentham-v10-latin.zip > bentham-v10-latin-temp.txt
unzip -l berkshire-swash-v8-latin.zip > berkshire-swash-v8-latin-temp.txt
unzip -l beth-ellen-v3-latin.zip > beth-ellen-v3-latin-temp.txt
unzip -l bevan-v11-latin.zip > bevan-v11-latin-temp.txt
unzip -l be-vietnam-v2-latin.zip > be-vietnam-v2-latin-temp.txt
unzip -l bigelow-rules-v9-latin.zip > bigelow-rules-v9-latin-temp.txt
unzip -l bigshot-one-v11-latin.zip > bigshot-one-v11-latin-temp.txt
unzip -l big-shoulders-display-v2-latin.zip > big-shoulders-display-v2-latin-temp.txt
unzip -l big-shoulders-text-v2-latin.zip > big-shoulders-text-v2-latin-temp.txt
unzip -l bilbo-swash-caps-v13-latin.zip > bilbo-swash-caps-v13-latin-temp.txt
unzip -l bilbo-v10-latin.zip > bilbo-v10-latin-temp.txt
unzip -l biorhyme-expanded-v6-latin.zip > biorhyme-expanded-v6-latin-temp.txt
unzip -l biorhyme-v5-latin.zip > biorhyme-v5-latin-temp.txt
unzip -l biryani-v5-latin.zip > biryani-v5-latin-temp.txt
unzip -l bitter-v16-latin.zip > bitter-v16-latin-temp.txt
unzip -l black-and-white-picture-v8-latin.zip > black-and-white-picture-v8-latin-temp.txt
unzip -l black-han-sans-v8-latin.zip > black-han-sans-v8-latin-temp.txt
unzip -l black-ops-one-v11-latin.zip > black-ops-one-v11-latin-temp.txt
unzip -l blinker-v4-latin.zip > blinker-v4-latin-temp.txt
unzip -l bonbon-v12-latin.zip > bonbon-v12-latin-temp.txt
unzip -l boogaloo-v11-latin.zip > boogaloo-v11-latin-temp.txt
unzip -l bowlby-one-sc-v11-latin.zip > bowlby-one-sc-v11-latin-temp.txt
unzip -l bowlby-one-v12-latin.zip > bowlby-one-v12-latin-temp.txt
unzip -l brawler-v11-latin.zip > brawler-v11-latin-temp.txt
unzip -l bree-serif-v9-latin.zip > bree-serif-v9-latin-temp.txt
unzip -l bubblegum-sans-v9-latin.zip > bubblegum-sans-v9-latin-temp.txt
unzip -l bubbler-one-v9-latin.zip > bubbler-one-v9-latin-temp.txt
unzip -l buda-v11-latin.zip > buda-v11-latin-temp.txt
unzip -l buenard-v12-latin.zip > buenard-v12-latin-temp.txt
unzip -l bungee-hairline-v6-latin.zip > bungee-hairline-v6-latin-temp.txt
unzip -l bungee-inline-v6-latin.zip > bungee-inline-v6-latin-temp.txt
unzip -l bungee-outline-v6-latin.zip > bungee-outline-v6-latin-temp.txt
unzip -l bungee-shade-v6-latin.zip > bungee-shade-v6-latin-temp.txt
unzip -l bungee-v5-latin.zip > bungee-v5-latin-temp.txt
unzip -l butcherman-v12-latin.zip > butcherman-v12-latin-temp.txt
unzip -l butterfly-kids-v9-latin.zip > butterfly-kids-v9-latin-temp.txt
unzip -l cabin-condensed-v13-latin.zip > cabin-condensed-v13-latin-temp.txt
unzip -l cabin-sketch-v13-latin.zip > cabin-sketch-v13-latin-temp.txt
unzip -l cabin-v14-latin.zip > cabin-v14-latin-temp.txt
unzip -l caesar-dressing-v9-latin.zip > caesar-dressing-v9-latin-temp.txt
unzip -l cagliostro-v9-latin.zip > cagliostro-v9-latin-temp.txt
unzip -l cairo-v7-latin.zip > cairo-v7-latin-temp.txt
unzip -l caladea-v2-latin.zip > caladea-v2-latin-temp.txt
unzip -l calistoga-v2-latin.zip > calistoga-v2-latin-temp.txt
unzip -l calligraffitti-v12-latin.zip > calligraffitti-v12-latin-temp.txt
unzip -l cambay-v7-latin.zip > cambay-v7-latin-temp.txt
unzip -l cambo-v9-latin.zip > cambo-v9-latin-temp.txt
unzip -l candal-v9-latin.zip > candal-v9-latin-temp.txt
unzip -l cantarell-v9-latin.zip > cantarell-v9-latin-temp.txt
unzip -l cantata-one-v9-latin.zip > cantata-one-v9-latin-temp.txt
unzip -l cantora-one-v10-latin.zip > cantora-one-v10-latin-temp.txt
unzip -l capriola-v7-latin.zip > capriola-v7-latin-temp.txt
unzip -l cardo-v11-latin.zip > cardo-v11-latin-temp.txt
unzip -l carme-v11-latin.zip > carme-v11-latin-temp.txt
unzip -l carrois-gothic-sc-v10-latin.zip > carrois-gothic-sc-v10-latin-temp.txt
unzip -l carrois-gothic-v11-latin.zip > carrois-gothic-v11-latin-temp.txt
unzip -l carter-one-v11-latin.zip > carter-one-v11-latin-temp.txt
unzip -l catamaran-v7-latin.zip > catamaran-v7-latin-temp.txt
unzip -l caudex-v9-latin.zip > caudex-v9-latin-temp.txt
unzip -l caveat-brush-v5-latin.zip > caveat-brush-v5-latin-temp.txt
unzip -l caveat-v7-latin.zip > caveat-v7-latin-temp.txt
unzip -l cedarville-cursive-v11-latin.zip > cedarville-cursive-v11-latin-temp.txt
unzip -l ceviche-one-v11-latin.zip > ceviche-one-v11-latin-temp.txt
unzip -l chakra-petch-v3-latin.zip > chakra-petch-v3-latin-temp.txt
unzip -l changa-one-v12-latin.zip > changa-one-v12-latin-temp.txt
unzip -l changa-v10-latin.zip > changa-v10-latin-temp.txt
unzip -l chango-v9-latin.zip > chango-v9-latin-temp.txt
unzip -l charmonman-v3-latin.zip > charmonman-v3-latin-temp.txt
unzip -l charm-v5-latin.zip > charm-v5-latin-temp.txt
unzip -l chathura-v6-latin.zip > chathura-v6-latin-temp.txt
unzip -l chau-philomene-one-v10-latin.zip > chau-philomene-one-v10-latin-temp.txt
unzip -l chela-one-v9-latin.zip > chela-one-v9-latin-temp.txt
unzip -l chelsea-market-v8-latin.zip > chelsea-market-v8-latin-temp.txt
unzip -l cherry-cream-soda-v11-latin.zip > cherry-cream-soda-v11-latin-temp.txt
unzip -l cherry-swash-v9-latin.zip > cherry-swash-v9-latin-temp.txt
unzip -l chewy-v11-latin.zip > chewy-v11-latin-temp.txt
unzip -l chicle-v9-latin.zip > chicle-v9-latin-temp.txt
unzip -l chilanka-v6-latin.zip > chilanka-v6-latin-temp.txt
unzip -l chivo-v11-latin.zip > chivo-v11-latin-temp.txt
unzip -l chonburi-v5-latin.zip > chonburi-v5-latin-temp.txt
unzip -l cinzel-decorative-v8-latin.zip > cinzel-decorative-v8-latin-temp.txt
unzip -l cinzel-v9-latin.zip > cinzel-v9-latin-temp.txt
unzip -l clicker-script-v8-latin.zip > clicker-script-v8-latin-temp.txt
unzip -l coda-caption-v13-latin.zip > coda-caption-v13-latin-temp.txt
unzip -l coda-v15-latin.zip > coda-v15-latin-temp.txt
unzip -l codystar-v8-latin.zip > codystar-v8-latin-temp.txt
unzip -l coiny-v6-latin.zip > coiny-v6-latin-temp.txt
unzip -l combo-v9-latin.zip > combo-v9-latin-temp.txt
unzip -l comfortaa-v29-latin.zip > comfortaa-v29-latin-temp.txt
unzip -l comic-neue-v2-latin.zip > comic-neue-v2-latin-temp.txt
unzip -l coming-soon-v12-latin.zip > coming-soon-v12-latin-temp.txt
unzip -l concert-one-v10-latin.zip > concert-one-v10-latin-temp.txt
unzip -l condiment-v8-latin.zip > condiment-v8-latin-temp.txt
unzip -l contrail-one-v10-latin.zip > contrail-one-v10-latin-temp.txt
unzip -l convergence-v9-latin.zip > convergence-v9-latin-temp.txt
unzip -l cookie-v11-latin.zip > cookie-v11-latin-temp.txt
unzip -l copse-v10-latin.zip > copse-v10-latin-temp.txt
unzip -l corben-v14-latin.zip > corben-v14-latin-temp.txt
unzip -l cormorant-garamond-v7-latin.zip > cormorant-garamond-v7-latin-temp.txt
unzip -l cormorant-infant-v8-latin.zip > cormorant-infant-v8-latin-temp.txt
unzip -l cormorant-sc-v8-latin.zip > cormorant-sc-v8-latin-temp.txt
unzip -l cormorant-unicase-v8-latin.zip > cormorant-unicase-v8-latin-temp.txt
unzip -l cormorant-upright-v6-latin.zip > cormorant-upright-v6-latin-temp.txt
unzip -l cormorant-v8-latin.zip > cormorant-v8-latin-temp.txt
unzip -l courgette-v7-latin.zip > courgette-v7-latin-temp.txt
unzip -l courier-prime-v2-latin.zip > courier-prime-v2-latin-temp.txt
unzip -l cousine-v14-latin.zip > cousine-v14-latin-temp.txt
unzip -l coustard-v11-latin.zip > coustard-v11-latin-temp.txt
unzip -l covered-by-your-grace-v9-latin.zip > covered-by-your-grace-v9-latin-temp.txt
unzip -l crafty-girls-v10-latin.zip > crafty-girls-v10-latin-temp.txt
unzip -l creepster-v9-latin.zip > creepster-v9-latin-temp.txt
unzip -l crete-round-v8-latin.zip > crete-round-v8-latin-temp.txt
unzip -l crimson-pro-v13-latin.zip > crimson-pro-v13-latin-temp.txt
unzip -l crimson-text-v10-latin.zip > crimson-text-v10-latin-temp.txt
unzip -l croissant-one-v8-latin.zip > croissant-one-v8-latin-temp.txt
unzip -l crushed-v11-latin.zip > crushed-v11-latin-temp.txt
unzip -l cuprum-v11-latin.zip > cuprum-v11-latin-temp.txt
unzip -l cute-font-v8-latin.zip > cute-font-v8-latin-temp.txt
unzip -l cutive-mono-v8-latin.zip > cutive-mono-v8-latin-temp.txt
unzip -l cutive-v12-latin.zip > cutive-v12-latin-temp.txt
unzip -l damion-v9-latin.zip > damion-v9-latin-temp.txt
unzip -l dancing-script-v15-latin.zip > dancing-script-v15-latin-temp.txt
unzip -l darker-grotesque-v2-latin.zip > darker-grotesque-v2-latin-temp.txt
unzip -l david-libre-v5-latin.zip > david-libre-v5-latin-temp.txt
unzip -l dawning-of-a-new-day-v11-latin.zip > dawning-of-a-new-day-v11-latin-temp.txt
unzip -l days-one-v9-latin.zip > days-one-v9-latin-temp.txt
unzip -l dekko-v7-latin.zip > dekko-v7-latin-temp.txt
unzip -l delius-swash-caps-v12-latin.zip > delius-swash-caps-v12-latin-temp.txt
unzip -l delius-unicase-v14-latin.zip > delius-unicase-v14-latin-temp.txt
unzip -l delius-v10-latin.zip > delius-v10-latin-temp.txt
unzip -l della-respira-v8-latin.zip > della-respira-v8-latin-temp.txt
unzip -l denk-one-v8-latin.zip > denk-one-v8-latin-temp.txt
unzip -l devonshire-v9-latin.zip > devonshire-v9-latin-temp.txt
unzip -l dhurjati-v8-latin.zip > dhurjati-v8-latin-temp.txt
unzip -l didact-gothic-v13-latin.zip > didact-gothic-v13-latin-temp.txt
unzip -l diplomata-sc-v9-latin.zip > diplomata-sc-v9-latin-temp.txt
unzip -l diplomata-v12-latin.zip > diplomata-v12-latin-temp.txt
unzip -l dm-mono-v2-latin.zip > dm-mono-v2-latin-temp.txt
unzip -l dm-sans-v4-latin.zip > dm-sans-v4-latin-temp.txt
unzip -l dm-serif-display-v4-latin.zip > dm-serif-display-v4-latin-temp.txt
unzip -l dm-serif-text-v4-latin.zip > dm-serif-text-v4-latin-temp.txt
unzip -l do-hyeon-v11-latin.zip > do-hyeon-v11-latin-temp.txt
unzip -l dokdo-v8-latin.zip > dokdo-v8-latin-temp.txt
unzip -l domine-v7-latin.zip > domine-v7-latin-temp.txt
unzip -l donegal-one-v8-latin.zip > donegal-one-v8-latin-temp.txt
unzip -l doppio-one-v8-latin.zip > doppio-one-v8-latin-temp.txt
unzip -l dorsa-v11-latin.zip > dorsa-v11-latin-temp.txt
unzip -l dosis-v18-latin.zip > dosis-v18-latin-temp.txt
unzip -l dr-sugiyama-v10-latin.zip > dr-sugiyama-v10-latin-temp.txt
unzip -l duru-sans-v14-latin.zip > duru-sans-v14-latin-temp.txt
unzip -l dynalight-v9-latin.zip > dynalight-v9-latin-temp.txt
unzip -l eagle-lake-v8-latin.zip > eagle-lake-v8-latin-temp.txt
unzip -l east-sea-dokdo-v8-latin.zip > east-sea-dokdo-v8-latin-temp.txt
unzip -l eater-v9-latin.zip > eater-v9-latin-temp.txt
unzip -l eb-garamond-v14-latin.zip > eb-garamond-v14-latin-temp.txt
unzip -l economica-v7-latin.zip > economica-v7-latin-temp.txt
unzip -l eczar-v8-latin.zip > eczar-v8-latin-temp.txt
unzip -l electrolize-v8-latin.zip > electrolize-v8-latin-temp.txt
unzip -l el-messiri-v6-latin.zip > el-messiri-v6-latin-temp.txt
unzip -l elsie-swash-caps-v9-latin.zip > elsie-swash-caps-v9-latin-temp.txt
unzip -l elsie-v10-latin.zip > elsie-v10-latin-temp.txt
unzip -l emblema-one-v9-latin.zip > emblema-one-v9-latin-temp.txt
unzip -l emilys-candy-v8-latin.zip > emilys-candy-v8-latin-temp.txt
unzip -l encode-sans-condensed-v4-latin.zip > encode-sans-condensed-v4-latin-temp.txt
unzip -l encode-sans-expanded-v5-latin.zip > encode-sans-expanded-v5-latin-temp.txt
unzip -l encode-sans-semi-condensed-v5-latin.zip > encode-sans-semi-condensed-v5-latin-temp.txt
unzip -l encode-sans-semi-expanded-v6-latin.zip > encode-sans-semi-expanded-v6-latin-temp.txt
unzip -l encode-sans-v7-latin.zip > encode-sans-v7-latin-temp.txt
unzip -l engagement-v10-latin.zip > engagement-v10-latin-temp.txt
unzip -l englebert-v8-latin.zip > englebert-v8-latin-temp.txt
unzip -l enriqueta-v9-latin.zip > enriqueta-v9-latin-temp.txt
unzip -l epilogue-v1-latin.zip > epilogue-v1-latin-temp.txt
unzip -l erica-one-v11-latin.zip > erica-one-v11-latin-temp.txt
unzip -l esteban-v9-latin.zip > esteban-v9-latin-temp.txt
unzip -l euphoria-script-v9-latin.zip > euphoria-script-v9-latin-temp.txt
unzip -l ewert-v8-latin.zip > ewert-v8-latin-temp.txt
unzip -l exo-2-v9-latin.zip > exo-2-v9-latin-temp.txt
unzip -l exo-v11-latin.zip > exo-v11-latin-temp.txt
unzip -l expletus-sans-v14-latin.zip > expletus-sans-v14-latin-temp.txt
unzip -l fahkwang-v4-latin.zip > fahkwang-v4-latin-temp.txt
unzip -l fanwood-text-v10-latin.zip > fanwood-text-v10-latin-temp.txt
unzip -l farro-v2-latin.zip > farro-v2-latin-temp.txt
unzip -l farsan-v6-latin.zip > farsan-v6-latin-temp.txt
unzip -l fascinate-inline-v10-latin.zip > fascinate-inline-v10-latin-temp.txt
unzip -l fascinate-v9-latin.zip > fascinate-v9-latin-temp.txt
unzip -l faster-one-v12-latin.zip > faster-one-v12-latin-temp.txt
unzip -l fauna-one-v7-latin.zip > fauna-one-v7-latin-temp.txt
unzip -l faustina-v7-latin.zip > faustina-v7-latin-temp.txt
unzip -l federant-v13-latin.zip > federant-v13-latin-temp.txt
unzip -l federo-v12-latin.zip > federo-v12-latin-temp.txt
unzip -l felipa-v7-latin.zip > felipa-v7-latin-temp.txt
unzip -l fenix-v8-latin.zip > fenix-v8-latin-temp.txt
unzip -l finger-paint-v10-latin.zip > finger-paint-v10-latin-temp.txt
unzip -l fira-code-v9-latin.zip > fira-code-v9-latin-temp.txt
unzip -l fira-mono-v8-latin.zip > fira-mono-v8-latin-temp.txt
unzip -l fira-sans-condensed-v4-latin.zip > fira-sans-condensed-v4-latin-temp.txt
unzip -l fira-sans-extra-condensed-v4-latin.zip > fira-sans-extra-condensed-v4-latin-temp.txt
unzip -l fira-sans-v10-latin.zip > fira-sans-v10-latin-temp.txt
unzip -l fjalla-one-v7-latin.zip > fjalla-one-v7-latin-temp.txt
unzip -l fjord-one-v9-latin.zip > fjord-one-v9-latin-temp.txt
unzip -l flamenco-v11-latin.zip > flamenco-v11-latin-temp.txt
unzip -l flavors-v10-latin.zip > flavors-v10-latin-temp.txt
unzip -l fondamento-v10-latin.zip > fondamento-v10-latin-temp.txt
unzip -l fontdiner-swanky-v11-latin.zip > fontdiner-swanky-v11-latin-temp.txt
unzip -l forum-v10-latin.zip > forum-v10-latin-temp.txt
unzip -l francois-one-v14-latin.zip > francois-one-v14-latin-temp.txt
unzip -l frank-ruhl-libre-v5-latin.zip > frank-ruhl-libre-v5-latin-temp.txt
unzip -l freckle-face-v9-latin.zip > freckle-face-v9-latin-temp.txt
unzip -l fredericka-the-great-v9-latin.zip > fredericka-the-great-v9-latin-temp.txt
unzip -l fredoka-one-v7-latin.zip > fredoka-one-v7-latin-temp.txt
unzip -l fresca-v9-latin.zip > fresca-v9-latin-temp.txt
unzip -l frijole-v9-latin.zip > frijole-v9-latin-temp.txt
unzip -l fruktur-v13-latin.zip > fruktur-v13-latin-temp.txt
unzip -l fugaz-one-v9-latin.zip > fugaz-one-v9-latin-temp.txt
unzip -l gabriela-v9-latin.zip > gabriela-v9-latin-temp.txt
unzip -l gaegu-v8-latin.zip > gaegu-v8-latin-temp.txt
unzip -l gafata-v9-latin.zip > gafata-v9-latin-temp.txt
unzip -l galada-v5-latin.zip > galada-v5-latin-temp.txt
unzip -l galdeano-v10-latin.zip > galdeano-v10-latin-temp.txt
unzip -l galindo-v8-latin.zip > galindo-v8-latin-temp.txt
unzip -l gamja-flower-v8-latin.zip > gamja-flower-v8-latin-temp.txt
unzip -l gayathri-v2-latin.zip > gayathri-v2-latin-temp.txt
unzip -l gelasio-v1-latin.zip > gelasio-v1-latin-temp.txt
unzip -l gentium-basic-v11-latin.zip > gentium-basic-v11-latin-temp.txt
unzip -l gentium-book-basic-v10-latin.zip > gentium-book-basic-v10-latin-temp.txt
unzip -l geostar-fill-v11-latin.zip > geostar-fill-v11-latin-temp.txt
unzip -l geostar-v11-latin.zip > geostar-v11-latin-temp.txt
unzip -l geo-v12-latin.zip > geo-v12-latin-temp.txt
unzip -l germania-one-v8-latin.zip > germania-one-v8-latin-temp.txt
unzip -l gidugu-v7-latin.zip > gidugu-v7-latin-temp.txt
unzip -l gilda-display-v8-latin.zip > gilda-display-v8-latin-temp.txt
unzip -l girassol-v2-latin.zip > girassol-v2-latin-temp.txt
unzip -l give-you-glory-v10-latin.zip > give-you-glory-v10-latin-temp.txt
unzip -l glass-antiqua-v8-latin.zip > glass-antiqua-v8-latin-temp.txt
unzip -l glegoo-v9-latin.zip > glegoo-v9-latin-temp.txt
unzip -l gloria-hallelujah-v11-latin.zip > gloria-hallelujah-v11-latin-temp.txt
unzip -l goblin-one-v10-latin.zip > goblin-one-v10-latin-temp.txt
unzip -l gochi-hand-v10-latin.zip > gochi-hand-v10-latin-temp.txt
unzip -l gorditas-v8-latin.zip > gorditas-v8-latin-temp.txt
unzip -l gothic-a1-v8-latin.zip > gothic-a1-v8-latin-temp.txt
unzip -l gotu-v1-latin.zip > gotu-v1-latin-temp.txt
unzip -l goudy-bookletter-1911-v10-latin.zip > goudy-bookletter-1911-v10-latin-temp.txt
unzip -l graduate-v7-latin.zip > graduate-v7-latin-temp.txt
unzip -l grand-hotel-v8-latin.zip > grand-hotel-v8-latin-temp.txt
unzip -l gravitas-one-v10-latin.zip > gravitas-one-v10-latin-temp.txt
unzip -l great-vibes-v7-latin.zip > great-vibes-v7-latin-temp.txt
unzip -l grenze-gotisch-v1-latin.zip > grenze-gotisch-v1-latin-temp.txt
unzip -l grenze-v2-latin.zip > grenze-v2-latin-temp.txt
unzip -l griffy-v9-latin.zip > griffy-v9-latin-temp.txt
unzip -l gruppo-v10-latin.zip > gruppo-v10-latin-temp.txt
unzip -l gudea-v9-latin.zip > gudea-v9-latin-temp.txt
unzip -l gugi-v8-latin.zip > gugi-v8-latin-temp.txt
unzip -l gupter-v2-latin.zip > gupter-v2-latin-temp.txt
unzip -l gurajada-v8-latin.zip > gurajada-v8-latin-temp.txt
unzip -l habibi-v9-latin.zip > habibi-v9-latin-temp.txt
unzip -l halant-v7-latin.zip > halant-v7-latin-temp.txt
unzip -l hammersmith-one-v10-latin.zip > hammersmith-one-v10-latin-temp.txt
unzip -l hanalei-fill-v9-latin.zip > hanalei-fill-v9-latin-temp.txt
unzip -l hanalei-v11-latin.zip > hanalei-v11-latin-temp.txt
unzip -l handlee-v8-latin.zip > handlee-v8-latin-temp.txt
unzip -l happy-monkey-v9-latin.zip > happy-monkey-v9-latin-temp.txt
unzip -l harmattan-v8-latin.zip > harmattan-v8-latin-temp.txt
unzip -l headland-one-v8-latin.zip > headland-one-v8-latin-temp.txt
unzip -l heebo-v9-latin.zip > heebo-v9-latin-temp.txt
unzip -l henny-penny-v8-latin.zip > henny-penny-v8-latin-temp.txt
unzip -l hepta-slab-v8-latin.zip > hepta-slab-v8-latin-temp.txt
unzip -l herr-von-muellerhoff-v10-latin.zip > herr-von-muellerhoff-v10-latin-temp.txt
unzip -l hi-melody-v8-latin.zip > hi-melody-v8-latin-temp.txt
unzip -l hind-guntur-v5-latin.zip > hind-guntur-v5-latin-temp.txt
unzip -l hind-madurai-v5-latin.zip > hind-madurai-v5-latin-temp.txt
unzip -l hind-siliguri-v6-latin.zip > hind-siliguri-v6-latin-temp.txt
unzip -l hind-v10-latin.zip > hind-v10-latin-temp.txt
unzip -l hind-vadodara-v6-latin.zip > hind-vadodara-v6-latin-temp.txt
unzip -l holtwood-one-sc-v10-latin.zip > holtwood-one-sc-v10-latin-temp.txt
unzip -l homemade-apple-v10-latin.zip > homemade-apple-v10-latin-temp.txt
unzip -l homenaje-v10-latin.zip > homenaje-v10-latin-temp.txt
unzip -l ibarra-real-nova-v2-latin.zip > ibarra-real-nova-v2-latin-temp.txt
unzip -l ibm-plex-mono-v5-latin.zip > ibm-plex-mono-v5-latin-temp.txt
unzip -l ibm-plex-sans-condensed-v7-latin.zip > ibm-plex-sans-condensed-v7-latin-temp.txt
unzip -l ibm-plex-sans-v7-latin.zip > ibm-plex-sans-v7-latin-temp.txt
unzip -l ibm-plex-serif-v8-latin.zip > ibm-plex-serif-v8-latin-temp.txt
unzip -l iceberg-v8-latin.zip > iceberg-v8-latin-temp.txt
unzip -l iceland-v9-latin.zip > iceland-v9-latin-temp.txt
unzip -l im-fell-double-pica-sc-v10-latin.zip > im-fell-double-pica-sc-v10-latin-temp.txt
unzip -l im-fell-double-pica-v10-latin.zip > im-fell-double-pica-v10-latin-temp.txt
unzip -l im-fell-dw-pica-sc-v10-latin.zip > im-fell-dw-pica-sc-v10-latin-temp.txt
unzip -l im-fell-dw-pica-v10-latin.zip > im-fell-dw-pica-v10-latin-temp.txt
unzip -l im-fell-english-sc-v10-latin.zip > im-fell-english-sc-v10-latin-temp.txt
unzip -l im-fell-english-v10-latin.zip > im-fell-english-v10-latin-temp.txt
unzip -l im-fell-french-canon-sc-v10-latin.zip > im-fell-french-canon-sc-v10-latin-temp.txt
unzip -l im-fell-french-canon-v10-latin.zip > im-fell-french-canon-v10-latin-temp.txt
unzip -l im-fell-great-primer-sc-v10-latin.zip > im-fell-great-primer-sc-v10-latin-temp.txt
unzip -l im-fell-great-primer-v10-latin.zip > im-fell-great-primer-v10-latin-temp.txt
unzip -l imprima-v9-latin.zip > imprima-v9-latin-temp.txt
unzip -l inconsolata-v20-latin.zip > inconsolata-v20-latin-temp.txt
unzip -l inder-v9-latin.zip > inder-v9-latin-temp.txt
unzip -l indie-flower-v11-latin.zip > indie-flower-v11-latin-temp.txt
unzip -l inika-v9-latin.zip > inika-v9-latin-temp.txt
unzip -l inknut-antiqua-v6-latin.zip > inknut-antiqua-v6-latin-temp.txt
unzip -l inria-sans-v2-latin.zip > inria-sans-v2-latin-temp.txt
unzip -l inria-serif-v2-latin.zip > inria-serif-v2-latin-temp.txt
unzip -l inter-v2-latin.zip > inter-v2-latin-temp.txt
unzip -l irish-grover-v10-latin.zip > irish-grover-v10-latin-temp.txt
unzip -l istok-web-v14-latin.zip > istok-web-v14-latin-temp.txt
unzip -l italiana-v9-latin.zip > italiana-v9-latin-temp.txt
unzip -l italianno-v9-latin.zip > italianno-v9-latin-temp.txt
unzip -l itim-v4-latin.zip > itim-v4-latin-temp.txt
unzip -l jacques-francois-shadow-v9-latin.zip > jacques-francois-shadow-v9-latin-temp.txt
unzip -l jacques-francois-v8-latin.zip > jacques-francois-v8-latin-temp.txt
unzip -l jaldi-v6-latin.zip > jaldi-v6-latin-temp.txt
unzip -l jim-nightshade-v8-latin.zip > jim-nightshade-v8-latin-temp.txt
unzip -l jockey-one-v9-latin.zip > jockey-one-v9-latin-temp.txt
unzip -l jolly-lodger-v8-latin.zip > jolly-lodger-v8-latin-temp.txt
unzip -l jomhuria-v8-latin.zip > jomhuria-v8-latin-temp.txt
unzip -l jomolhari-v2-latin.zip > jomolhari-v2-latin-temp.txt
unzip -l josefin-sans-v16-latin.zip > josefin-sans-v16-latin-temp.txt
unzip -l josefin-slab-v10-latin.zip > josefin-slab-v10-latin-temp.txt
unzip -l jost-v3-latin.zip > jost-v3-latin-temp.txt
unzip -l joti-one-v9-latin.zip > joti-one-v9-latin-temp.txt
unzip -l jua-v8-latin.zip > jua-v8-latin-temp.txt
unzip -l judson-v12-latin.zip > judson-v12-latin-temp.txt
unzip -l julee-v10-latin.zip > julee-v10-latin-temp.txt
unzip -l julius-sans-one-v8-latin.zip > julius-sans-one-v8-latin-temp.txt
unzip -l junge-v8-latin.zip > junge-v8-latin-temp.txt
unzip -l jura-v15-latin.zip > jura-v15-latin-temp.txt
unzip -l just-another-hand-v11-latin.zip > just-another-hand-v11-latin-temp.txt
unzip -l just-me-again-down-here-v12-latin.zip > just-me-again-down-here-v12-latin-temp.txt
unzip -l k2d-v4-latin.zip > k2d-v4-latin-temp.txt
unzip -l kadwa-v4-latin.zip > kadwa-v4-latin-temp.txt
unzip -l kalam-v10-latin.zip > kalam-v10-latin-temp.txt
unzip -l kameron-v10-latin.zip > kameron-v10-latin-temp.txt
unzip -l kanit-v6-latin.zip > kanit-v6-latin-temp.txt
unzip -l karla-v13-latin.zip > karla-v13-latin-temp.txt
unzip -l karma-v10-latin.zip > karma-v10-latin-temp.txt
unzip -l katibeh-v7-latin.zip > katibeh-v7-latin-temp.txt
unzip -l kaushan-script-v8-latin.zip > kaushan-script-v8-latin-temp.txt
unzip -l kavivanar-v6-latin.zip > kavivanar-v6-latin-temp.txt
unzip -l kavoon-v9-latin.zip > kavoon-v9-latin-temp.txt
unzip -l keania-one-v8-latin.zip > keania-one-v8-latin-temp.txt
unzip -l kelly-slab-v11-latin.zip > kelly-slab-v11-latin-temp.txt
unzip -l kenia-v12-latin.zip > kenia-v12-latin-temp.txt
unzip -l khand-v8-latin.zip > khand-v8-latin-temp.txt
unzip -l khula-v5-latin.zip > khula-v5-latin-temp.txt
unzip -l kirang-haerang-v8-latin.zip > kirang-haerang-v8-latin-temp.txt
unzip -l kite-one-v8-latin.zip > kite-one-v8-latin-temp.txt
unzip -l knewave-v8-latin.zip > knewave-v8-latin-temp.txt
unzip -l kodchasan-v4-latin.zip > kodchasan-v4-latin-temp.txt
unzip -l koho-v4-latin.zip > koho-v4-latin-temp.txt
unzip -l kosugi-maru-v6-latin.zip > kosugi-maru-v6-latin-temp.txt
unzip -l kosugi-v6-latin.zip > kosugi-v6-latin-temp.txt
unzip -l kotta-one-v8-latin.zip > kotta-one-v8-latin-temp.txt
unzip -l kranky-v11-latin.zip > kranky-v11-latin-temp.txt
unzip -l kreon-v23-latin.zip > kreon-v23-latin-temp.txt
unzip -l kristi-v12-latin.zip > kristi-v12-latin-temp.txt
unzip -l krona-one-v8-latin.zip > krona-one-v8-latin-temp.txt
unzip -l krub-v3-latin.zip > krub-v3-latin-temp.txt
unzip -l kulim-park-v2-latin.zip > kulim-park-v2-latin-temp.txt
unzip -l kumar-one-outline-v6-latin.zip > kumar-one-outline-v6-latin-temp.txt
unzip -l kumar-one-v5-latin.zip > kumar-one-v5-latin-temp.txt
unzip -l kurale-v6-latin.zip > kurale-v6-latin-temp.txt
unzip -l la-belle-aurore-v11-latin.zip > la-belle-aurore-v11-latin-temp.txt
unzip -l lacquer-v3-latin.zip > lacquer-v3-latin-temp.txt
unzip -l laila-v7-latin.zip > laila-v7-latin-temp.txt
unzip -l lakki-reddy-v7-latin.zip > lakki-reddy-v7-latin-temp.txt
unzip -l lalezar-v6-latin.zip > lalezar-v6-latin-temp.txt
unzip -l lancelot-v10-latin.zip > lancelot-v10-latin-temp.txt
unzip -l lateef-v15-latin.zip > lateef-v15-latin-temp.txt
unzip -l lato-v16-latin.zip > lato-v16-latin-temp.txt
unzip -l league-script-v12-latin.zip > league-script-v12-latin-temp.txt
unzip -l leckerli-one-v10-latin.zip > leckerli-one-v10-latin-temp.txt
unzip -l ledger-v9-latin.zip > ledger-v9-latin-temp.txt
unzip -l lekton-v11-latin.zip > lekton-v11-latin-temp.txt
unzip -l lemonada-v11-latin.zip > lemonada-v11-latin-temp.txt
unzip -l lemon-v9-latin.zip > lemon-v9-latin-temp.txt
unzip -l lexend-deca-v1-latin.zip > lexend-deca-v1-latin-temp.txt
unzip -l lexend-exa-v1-latin.zip > lexend-exa-v1-latin-temp.txt
unzip -l lexend-giga-v1-latin.zip > lexend-giga-v1-latin-temp.txt
unzip -l lexend-mega-v1-latin.zip > lexend-mega-v1-latin-temp.txt
unzip -l lexend-peta-v1-latin.zip > lexend-peta-v1-latin-temp.txt
unzip -l lexend-tera-v1-latin.zip > lexend-tera-v1-latin-temp.txt
unzip -l lexend-zetta-v1-latin.zip > lexend-zetta-v1-latin-temp.txt
unzip -l libre-barcode-128-text-v10-latin.zip > libre-barcode-128-text-v10-latin-temp.txt
unzip -l libre-barcode-128-v10-latin.zip > libre-barcode-128-v10-latin-temp.txt
unzip -l libre-barcode-39-extended-text-v9-latin.zip > libre-barcode-39-extended-text-v9-latin-temp.txt
unzip -l libre-barcode-39-extended-v9-latin.zip > libre-barcode-39-extended-v9-latin-temp.txt
unzip -l libre-barcode-39-text-v10-latin.zip > libre-barcode-39-text-v10-latin-temp.txt
unzip -l libre-barcode-39-v10-latin.zip > libre-barcode-39-v10-latin-temp.txt
unzip -l libre-baskerville-v7-latin.zip > libre-baskerville-v7-latin-temp.txt
unzip -l libre-caslon-display-v2-latin.zip > libre-caslon-display-v2-latin-temp.txt
unzip -l libre-caslon-text-v2-latin.zip > libre-caslon-text-v2-latin-temp.txt
unzip -l libre-franklin-v4-latin.zip > libre-franklin-v4-latin-temp.txt
unzip -l life-savers-v11-latin.zip > life-savers-v11-latin-temp.txt
unzip -l lilita-one-v7-latin.zip > lilita-one-v7-latin-temp.txt
unzip -l lily-script-one-v8-latin.zip > lily-script-one-v8-latin-temp.txt
unzip -l limelight-v11-latin.zip > limelight-v11-latin-temp.txt
unzip -l linden-hill-v10-latin.zip > linden-hill-v10-latin-temp.txt
unzip -l literata-v16-latin.zip > literata-v16-latin-temp.txt
unzip -l liu-jian-mao-cao-v5-latin.zip > liu-jian-mao-cao-v5-latin-temp.txt
unzip -l livvic-v3-latin.zip > livvic-v3-latin-temp.txt
unzip -l lobster-two-v12-latin.zip > lobster-two-v12-latin-temp.txt
unzip -l lobster-v22-latin.zip > lobster-v22-latin-temp.txt
unzip -l londrina-outline-v11-latin.zip > londrina-outline-v11-latin-temp.txt
unzip -l londrina-shadow-v10-latin.zip > londrina-shadow-v10-latin-temp.txt
unzip -l londrina-sketch-v9-latin.zip > londrina-sketch-v9-latin-temp.txt
unzip -l londrina-solid-v9-latin.zip > londrina-solid-v9-latin-temp.txt
unzip -l long-cang-v5-latin.zip > long-cang-v5-latin-temp.txt
unzip -l lora-v16-latin.zip > lora-v16-latin-temp.txt
unzip -l loved-by-the-king-v10-latin.zip > loved-by-the-king-v10-latin-temp.txt
unzip -l lovers-quarrel-v8-latin.zip > lovers-quarrel-v8-latin-temp.txt
unzip -l love-ya-like-a-sister-v11-latin.zip > love-ya-like-a-sister-v11-latin-temp.txt
unzip -l luckiest-guy-v10-latin.zip > luckiest-guy-v10-latin-temp.txt
unzip -l lusitana-v7-latin.zip > lusitana-v7-latin-temp.txt
unzip -l lustria-v8-latin.zip > lustria-v8-latin-temp.txt
unzip -l macondo-swash-caps-v8-latin.zip > macondo-swash-caps-v8-latin-temp.txt
unzip -l macondo-v9-latin.zip > macondo-v9-latin-temp.txt
unzip -l mada-v8-latin.zip > mada-v8-latin-temp.txt
unzip -l magra-v9-latin.zip > magra-v9-latin-temp.txt
unzip -l maiden-orange-v11-latin.zip > maiden-orange-v11-latin-temp.txt
unzip -l maitree-v5-latin.zip > maitree-v5-latin-temp.txt
unzip -l major-mono-display-v5-latin.zip > major-mono-display-v5-latin-temp.txt
unzip -l mako-v12-latin.zip > mako-v12-latin-temp.txt
unzip -l mali-v3-latin.zip > mali-v3-latin-temp.txt
unzip -l mallanna-v8-latin.zip > mallanna-v8-latin-temp.txt
unzip -l mandali-v9-latin.zip > mandali-v9-latin-temp.txt
unzip -l manjari-v3-latin.zip > manjari-v3-latin-temp.txt
unzip -l manrope-v3-latin.zip > manrope-v3-latin-temp.txt
unzip -l mansalva-v2-latin.zip > mansalva-v2-latin-temp.txt
unzip -l manuale-v7-latin.zip > manuale-v7-latin-temp.txt
unzip -l marcellus-sc-v7-latin.zip > marcellus-sc-v7-latin-temp.txt
unzip -l marcellus-v7-latin.zip > marcellus-v7-latin-temp.txt
unzip -l marck-script-v10-latin.zip > marck-script-v10-latin-temp.txt
unzip -l margarine-v9-latin.zip > margarine-v9-latin-temp.txt
unzip -l markazi-text-v12-latin.zip > markazi-text-v12-latin-temp.txt
unzip -l marko-one-v10-latin.zip > marko-one-v10-latin-temp.txt
unzip -l marmelad-v10-latin.zip > marmelad-v10-latin-temp.txt
unzip -l martel-sans-v6-latin.zip > martel-sans-v6-latin-temp.txt
unzip -l martel-v4-latin.zip > martel-v4-latin-temp.txt
unzip -l marvel-v10-latin.zip > marvel-v10-latin-temp.txt
unzip -l ma-shan-zheng-v5-latin.zip > ma-shan-zheng-v5-latin-temp.txt
unzip -l mate-sc-v9-latin.zip > mate-sc-v9-latin-temp.txt
unzip -l mate-v9-latin.zip > mate-v9-latin-temp.txt
unzip -l maven-pro-v21-latin.zip > maven-pro-v21-latin-temp.txt
unzip -l mclaren-v8-latin.zip > mclaren-v8-latin-temp.txt
unzip -l meddon-v13-latin.zip > meddon-v13-latin-temp.txt
unzip -l medievalsharp-v12-latin.zip > medievalsharp-v12-latin-temp.txt
unzip -l medula-one-v10-latin.zip > medula-one-v10-latin-temp.txt
unzip -l meera-inimai-v5-latin.zip > meera-inimai-v5-latin-temp.txt
unzip -l megrim-v11-latin.zip > megrim-v11-latin-temp.txt
unzip -l meie-script-v8-latin.zip > meie-script-v8-latin-temp.txt
unzip -l merienda-one-v10-latin.zip > merienda-one-v10-latin-temp.txt
unzip -l merienda-v8-latin.zip > merienda-v8-latin-temp.txt
unzip -l merriweather-sans-v11-latin.zip > merriweather-sans-v11-latin-temp.txt
unzip -l merriweather-v21-latin.zip > merriweather-v21-latin-temp.txt
unzip -l metal-mania-v10-latin.zip > metal-mania-v10-latin-temp.txt
unzip -l metamorphous-v11-latin.zip > metamorphous-v11-latin-temp.txt
unzip -l metrophobic-v14-latin.zip > metrophobic-v14-latin-temp.txt
unzip -l michroma-v10-latin.zip > michroma-v10-latin-temp.txt
unzip -l milonga-v8-latin.zip > milonga-v8-latin-temp.txt
unzip -l miltonian-tattoo-v16-latin.zip > miltonian-tattoo-v16-latin-temp.txt
unzip -l miltonian-v14-latin.zip > miltonian-v14-latin-temp.txt
unzip -l mina-v4-latin.zip > mina-v4-latin-temp.txt
unzip -l miniver-v9-latin.zip > miniver-v9-latin-temp.txt
unzip -l miriam-libre-v6-latin.zip > miriam-libre-v6-latin-temp.txt
unzip -l mirza-v7-latin.zip > mirza-v7-latin-temp.txt
unzip -l miss-fajardose-v10-latin.zip > miss-fajardose-v10-latin-temp.txt
unzip -l mitr-v5-latin.zip > mitr-v5-latin-temp.txt
unzip -l modak-v5-latin.zip > modak-v5-latin-temp.txt
unzip -l modern-antiqua-v10-latin.zip > modern-antiqua-v10-latin-temp.txt
unzip -l mogra-v7-latin.zip > mogra-v7-latin-temp.txt
unzip -l molengo-v10-latin.zip > molengo-v10-latin-temp.txt
unzip -l molle-v9-latin.zip > molle-v9-latin-temp.txt
unzip -l monda-v9-latin.zip > monda-v9-latin-temp.txt
unzip -l monofett-v10-latin.zip > monofett-v10-latin-temp.txt
unzip -l monoton-v9-latin.zip > monoton-v9-latin-temp.txt
unzip -l monsieur-la-doulaise-v9-latin.zip > monsieur-la-doulaise-v9-latin-temp.txt
unzip -l montaga-v8-latin.zip > montaga-v8-latin-temp.txt
unzip -l montez-v11-latin.zip > montez-v11-latin-temp.txt
unzip -l montserrat-alternates-v11-latin.zip > montserrat-alternates-v11-latin-temp.txt
unzip -l montserrat-subrayada-v9-latin.zip > montserrat-subrayada-v9-latin-temp.txt
unzip -l montserrat-v14-latin.zip > montserrat-v14-latin-temp.txt
unzip -l mountains-of-christmas-v13-latin.zip > mountains-of-christmas-v13-latin-temp.txt
unzip -l mouse-memoirs-v8-latin.zip > mouse-memoirs-v8-latin-temp.txt
unzip -l m-plus-1p-v19-latin.zip > m-plus-1p-v19-latin-temp.txt
unzip -l m-plus-rounded-1c-v10-latin.zip > m-plus-rounded-1c-v10-latin-temp.txt
unzip -l mr-bedfort-v9-latin.zip > mr-bedfort-v9-latin-temp.txt
unzip -l mr-dafoe-v8-latin.zip > mr-dafoe-v8-latin-temp.txt
unzip -l mr-de-haviland-v9-latin.zip > mr-de-haviland-v9-latin-temp.txt
unzip -l mrs-saint-delafield-v7-latin.zip > mrs-saint-delafield-v7-latin-temp.txt
unzip -l mrs-sheppards-v9-latin.zip > mrs-sheppards-v9-latin-temp.txt
unzip -l mukta-mahee-v6-latin.zip > mukta-mahee-v6-latin-temp.txt
unzip -l mukta-malar-v6-latin.zip > mukta-malar-v6-latin-temp.txt
unzip -l mukta-v7-latin.zip > mukta-v7-latin-temp.txt
unzip -l mukta-vaani-v7-latin.zip > mukta-vaani-v7-latin-temp.txt
unzip -l mulish-v1-latin.zip > mulish-v1-latin-temp.txt
unzip -l museomoderno-v2-latin.zip > museomoderno-v2-latin-temp.txt
unzip -l mystery-quest-v8-latin.zip > mystery-quest-v8-latin-temp.txt
unzip -l nanum-brush-script-v17-latin.zip > nanum-brush-script-v17-latin-temp.txt
unzip -l nanum-gothic-coding-v14-latin.zip > nanum-gothic-coding-v14-latin-temp.txt
unzip -l nanum-gothic-v17-latin.zip > nanum-gothic-v17-latin-temp.txt
unzip -l nanum-myeongjo-v15-latin.zip > nanum-myeongjo-v15-latin-temp.txt
unzip -l nanum-pen-script-v15-latin.zip > nanum-pen-script-v15-latin-temp.txt
unzip -l neucha-v11-latin.zip > neucha-v11-latin-temp.txt
unzip -l neuton-v12-latin.zip > neuton-v12-latin-temp.txt
unzip -l new-rocker-v9-latin.zip > new-rocker-v9-latin-temp.txt
unzip -l news-cycle-v16-latin.zip > news-cycle-v16-latin-temp.txt
unzip -l niconne-v9-latin.zip > niconne-v9-latin-temp.txt
unzip -l niramit-v5-latin.zip > niramit-v5-latin-temp.txt
unzip -l nixie-one-v11-latin.zip > nixie-one-v11-latin-temp.txt
unzip -l nobile-v11-latin.zip > nobile-v11-latin-temp.txt
unzip -l norican-v8-latin.zip > norican-v8-latin-temp.txt
unzip -l nosifer-v9-latin.zip > nosifer-v9-latin-temp.txt
unzip -l notable-v5-latin.zip > notable-v5-latin-temp.txt
unzip -l nothing-you-could-do-v9-latin.zip > nothing-you-could-do-v9-latin-temp.txt
unzip -l noticia-text-v9-latin.zip > noticia-text-v9-latin-temp.txt
unzip -l noto-sans-hk-v5-latin.zip > noto-sans-hk-v5-latin-temp.txt
unzip -l noto-sans-jp-v25-latin.zip > noto-sans-jp-v25-latin-temp.txt
unzip -l noto-sans-kr-v12-latin.zip > noto-sans-kr-v12-latin-temp.txt
unzip -l noto-sans-sc-v11-latin.zip > noto-sans-sc-v11-latin-temp.txt
unzip -l noto-sans-tc-v10-latin.zip > noto-sans-tc-v10-latin-temp.txt
unzip -l noto-sans-v9-latin.zip > noto-sans-v9-latin-temp.txt
unzip -l noto-serif-jp-v7-latin.zip > noto-serif-jp-v7-latin-temp.txt
unzip -l noto-serif-kr-v6-latin.zip > noto-serif-kr-v6-latin-temp.txt
unzip -l noto-serif-sc-v7-latin.zip > noto-serif-sc-v7-latin-temp.txt
unzip -l noto-serif-tc-v7-latin.zip > noto-serif-tc-v7-latin-temp.txt
unzip -l noto-serif-v8-latin.zip > noto-serif-v8-latin-temp.txt
unzip -l nova-cut-v12-latin.zip > nova-cut-v12-latin-temp.txt
unzip -l nova-flat-v12-latin.zip > nova-flat-v12-latin-temp.txt
unzip -l nova-mono-v11-latin.zip > nova-mono-v11-latin-temp.txt
unzip -l nova-oval-v12-latin.zip > nova-oval-v12-latin-temp.txt
unzip -l nova-round-v12-latin.zip > nova-round-v12-latin-temp.txt
unzip -l nova-script-v13-latin.zip > nova-script-v13-latin-temp.txt
unzip -l nova-slim-v12-latin.zip > nova-slim-v12-latin-temp.txt
unzip -l nova-square-v13-latin.zip > nova-square-v13-latin-temp.txt
unzip -l ntr-v8-latin.zip > ntr-v8-latin-temp.txt
unzip -l numans-v10-latin.zip > numans-v10-latin-temp.txt
unzip -l nunito-sans-v5-latin.zip > nunito-sans-v5-latin-temp.txt
unzip -l nunito-v13-latin.zip > nunito-v13-latin-temp.txt
unzip -l odibee-sans-v2-latin.zip > odibee-sans-v2-latin-temp.txt
unzip -l offside-v8-latin.zip > offside-v8-latin-temp.txt
unzip -l oldenburg-v8-latin.zip > oldenburg-v8-latin-temp.txt
unzip -l old-standard-tt-v12-latin.zip > old-standard-tt-v12-latin-temp.txt
unzip -l oleo-script-swash-caps-v8-latin.zip > oleo-script-swash-caps-v8-latin-temp.txt
unzip -l oleo-script-v8-latin.zip > oleo-script-v8-latin-temp.txt
unzip -l open-sans-condensed-v14-latin.zip > open-sans-condensed-v14-latin-temp.txt
unzip -l open-sans-v17-latin.zip > open-sans-v17-latin-temp.txt
unzip -l oranienbaum-v8-latin.zip > oranienbaum-v8-latin-temp.txt
unzip -l orbitron-v16-latin.zip > orbitron-v16-latin-temp.txt
unzip -l oregano-v8-latin.zip > oregano-v8-latin-temp.txt
unzip -l orienta-v8-latin.zip > orienta-v8-latin-temp.txt
unzip -l original-surfer-v9-latin.zip > original-surfer-v9-latin-temp.txt
unzip -l oswald-v35-latin.zip > oswald-v35-latin-temp.txt
unzip -l overlock-sc-v9-latin.zip > overlock-sc-v9-latin-temp.txt
unzip -l overlock-v9-latin.zip > overlock-v9-latin-temp.txt
unzip -l overpass-mono-v5-latin.zip > overpass-mono-v5-latin-temp.txt
unzip -l overpass-v4-latin.zip > overpass-v4-latin-temp.txt
unzip -l over-the-rainbow-v11-latin.zip > over-the-rainbow-v11-latin-temp.txt
unzip -l ovo-v12-latin.zip > ovo-v12-latin-temp.txt
unzip -l oxanium-v2-latin.zip > oxanium-v2-latin-temp.txt
unzip -l oxygen-mono-v8-latin.zip > oxygen-mono-v8-latin-temp.txt
unzip -l oxygen-v9-latin.zip > oxygen-v9-latin-temp.txt
unzip -l pacifico-v16-latin.zip > pacifico-v16-latin-temp.txt
unzip -l padauk-v6-latin.zip > padauk-v6-latin-temp.txt
unzip -l palanquin-dark-v7-latin.zip > palanquin-dark-v7-latin-temp.txt
unzip -l palanquin-v5-latin.zip > palanquin-v5-latin-temp.txt
unzip -l pangolin-v6-latin.zip > pangolin-v6-latin-temp.txt
unzip -l paprika-v8-latin.zip > paprika-v8-latin-temp.txt
unzip -l parisienne-v7-latin.zip > parisienne-v7-latin-temp.txt
unzip -l passero-one-v12-latin.zip > passero-one-v12-latin-temp.txt
unzip -l passion-one-v10-latin.zip > passion-one-v10-latin-temp.txt
unzip -l pathway-gothic-one-v8-latin.zip > pathway-gothic-one-v8-latin-temp.txt
unzip -l patrick-hand-sc-v8-latin.zip > patrick-hand-sc-v8-latin-temp.txt
unzip -l patrick-hand-v13-latin.zip > patrick-hand-v13-latin-temp.txt
unzip -l pattaya-v5-latin.zip > pattaya-v5-latin-temp.txt
unzip -l patua-one-v10-latin.zip > patua-one-v10-latin-temp.txt
unzip -l pavanam-v5-latin.zip > pavanam-v5-latin-temp.txt
unzip -l paytone-one-v12-latin.zip > paytone-one-v12-latin-temp.txt
unzip -l peddana-v8-latin.zip > peddana-v8-latin-temp.txt
unzip -l peralta-v8-latin.zip > peralta-v8-latin-temp.txt
unzip -l permanent-marker-v9-latin.zip > permanent-marker-v9-latin-temp.txt
unzip -l petit-formal-script-v8-latin.zip > petit-formal-script-v8-latin-temp.txt
unzip -l petrona-v10-latin.zip > petrona-v10-latin-temp.txt
unzip -l philosopher-v12-latin.zip > philosopher-v12-latin-temp.txt
unzip -l piedra-v8-latin.zip > piedra-v8-latin-temp.txt
unzip -l pinyon-script-v10-latin.zip > pinyon-script-v10-latin-temp.txt
unzip -l pirata-one-v9-latin.zip > pirata-one-v9-latin-temp.txt
unzip -l plaster-v12-latin.zip > plaster-v12-latin-temp.txt
unzip -l playball-v9-latin.zip > playball-v9-latin-temp.txt
unzip -l playfair-display-sc-v9-latin.zip > playfair-display-sc-v9-latin-temp.txt
unzip -l playfair-display-v21-latin.zip > playfair-display-v21-latin-temp.txt
unzip -l play-v11-latin.zip > play-v11-latin-temp.txt
unzip -l podkova-v17-latin.zip > podkova-v17-latin-temp.txt
unzip -l poiret-one-v8-latin.zip > poiret-one-v8-latin-temp.txt
unzip -l poller-one-v10-latin.zip > poller-one-v10-latin-temp.txt
unzip -l poly-v11-latin.zip > poly-v11-latin-temp.txt
unzip -l pompiere-v10-latin.zip > pompiere-v10-latin-temp.txt
unzip -l pontano-sans-v7-latin.zip > pontano-sans-v7-latin-temp.txt
unzip -l poor-story-v8-latin.zip > poor-story-v8-latin-temp.txt
unzip -l poppins-v12-latin.zip > poppins-v12-latin-temp.txt
unzip -l port-lligat-sans-v9-latin.zip > port-lligat-sans-v9-latin-temp.txt
unzip -l port-lligat-slab-v9-latin.zip > port-lligat-slab-v9-latin-temp.txt
unzip -l pragati-narrow-v5-latin.zip > pragati-narrow-v5-latin-temp.txt
unzip -l prata-v11-latin.zip > prata-v11-latin-temp.txt
unzip -l press-start-2p-v8-latin.zip > press-start-2p-v8-latin-temp.txt
unzip -l pridi-v5-latin.zip > pridi-v5-latin-temp.txt
unzip -l princess-sofia-v9-latin.zip > princess-sofia-v9-latin-temp.txt
unzip -l prociono-v10-latin.zip > prociono-v10-latin-temp.txt
unzip -l prompt-v4-latin.zip > prompt-v4-latin-temp.txt
unzip -l prosto-one-v9-latin.zip > prosto-one-v9-latin-temp.txt
unzip -l proza-libre-v5-latin.zip > proza-libre-v5-latin-temp.txt
unzip -l pt-mono-v7-latin.zip > pt-mono-v7-latin-temp.txt
unzip -l pt-sans-caption-v12-latin.zip > pt-sans-caption-v12-latin-temp.txt
unzip -l pt-sans-narrow-v11-latin.zip > pt-sans-narrow-v11-latin-temp.txt
unzip -l pt-sans-v11-latin.zip > pt-sans-v11-latin-temp.txt
unzip -l pt-serif-caption-v11-latin.zip > pt-serif-caption-v11-latin-temp.txt
unzip -l pt-serif-v11-latin.zip > pt-serif-v11-latin-temp.txt
unzip -l public-sans-v4-latin.zip > public-sans-v4-latin-temp.txt
unzip -l puritan-v12-latin.zip > puritan-v12-latin-temp.txt
unzip -l purple-purse-v9-latin.zip > purple-purse-v9-latin-temp.txt
unzip -l quando-v9-latin.zip > quando-v9-latin-temp.txt
unzip -l quantico-v9-latin.zip > quantico-v9-latin-temp.txt
unzip -l quattrocento-sans-v12-latin.zip > quattrocento-sans-v12-latin-temp.txt
unzip -l quattrocento-v11-latin.zip > quattrocento-v11-latin-temp.txt
unzip -l questrial-v10-latin.zip > questrial-v10-latin-temp.txt
unzip -l quicksand-v21-latin.zip > quicksand-v21-latin-temp.txt
unzip -l quintessential-v8-latin.zip > quintessential-v8-latin-temp.txt
unzip -l qwigley-v10-latin.zip > qwigley-v10-latin-temp.txt
unzip -l racing-sans-one-v7-latin.zip > racing-sans-one-v7-latin-temp.txt
unzip -l radley-v15-latin.zip > radley-v15-latin-temp.txt
unzip -l rajdhani-v9-latin.zip > rajdhani-v9-latin-temp.txt
unzip -l rakkas-v7-latin.zip > rakkas-v7-latin-temp.txt
unzip -l raleway-dots-v8-latin.zip > raleway-dots-v8-latin-temp.txt
unzip -l raleway-v17-latin.zip > raleway-v17-latin-temp.txt
unzip -l ramabhadra-v9-latin.zip > ramabhadra-v9-latin-temp.txt
unzip -l ramaraja-v5-latin.zip > ramaraja-v5-latin-temp.txt
unzip -l rambla-v7-latin.zip > rambla-v7-latin-temp.txt
unzip -l rammetto-one-v9-latin.zip > rammetto-one-v9-latin-temp.txt
unzip -l ranchers-v8-latin.zip > ranchers-v8-latin-temp.txt
unzip -l rancho-v10-latin.zip > rancho-v10-latin-temp.txt
unzip -l ranga-v6-latin.zip > ranga-v6-latin-temp.txt
unzip -l rasa-v6-latin.zip > rasa-v6-latin-temp.txt
unzip -l rationale-v12-latin.zip > rationale-v12-latin-temp.txt
unzip -l ravi-prakash-v7-latin.zip > ravi-prakash-v7-latin-temp.txt
unzip -l recursive-v20-latin.zip > recursive-v20-latin-temp.txt
unzip -l red-hat-display-v3-latin.zip > red-hat-display-v3-latin-temp.txt
unzip -l red-hat-text-v3-latin.zip > red-hat-text-v3-latin-temp.txt
unzip -l redressed-v11-latin.zip > redressed-v11-latin-temp.txt
unzip -l red-rose-v1-latin.zip > red-rose-v1-latin-temp.txt
unzip -l reem-kufi-v7-latin.zip > reem-kufi-v7-latin-temp.txt
unzip -l reenie-beanie-v10-latin.zip > reenie-beanie-v10-latin-temp.txt
unzip -l revalia-v7-latin.zip > revalia-v7-latin-temp.txt
unzip -l rhodium-libre-v5-latin.zip > rhodium-libre-v5-latin-temp.txt
unzip -l ribeye-marrow-v10-latin.zip > ribeye-marrow-v10-latin-temp.txt
unzip -l ribeye-v9-latin.zip > ribeye-v9-latin-temp.txt
unzip -l righteous-v8-latin.zip > righteous-v8-latin-temp.txt
unzip -l risque-v8-latin.zip > risque-v8-latin-temp.txt
unzip -l roboto-condensed-v18-latin.zip > roboto-condensed-v18-latin-temp.txt
unzip -l roboto-mono-v12-latin.zip > roboto-mono-v12-latin-temp.txt
unzip -l roboto-slab-v12-latin.zip > roboto-slab-v12-latin-temp.txt
unzip -l roboto-v20-latin.zip > roboto-v20-latin-temp.txt
unzip -l rochester-v11-latin.zip > rochester-v11-latin-temp.txt
unzip -l rock-salt-v10-latin.zip > rock-salt-v10-latin-temp.txt
unzip -l rokkitt-v19-latin.zip > rokkitt-v19-latin-temp.txt
unzip -l romanesco-v9-latin.zip > romanesco-v9-latin-temp.txt
unzip -l ropa-sans-v9-latin.zip > ropa-sans-v9-latin-temp.txt
unzip -l rosario-v18-latin.zip > rosario-v18-latin-temp.txt
unzip -l rosarivo-v8-latin.zip > rosarivo-v8-latin-temp.txt
unzip -l rouge-script-v9-latin.zip > rouge-script-v9-latin-temp.txt
unzip -l rowdies-v1-latin.zip > rowdies-v1-latin-temp.txt
unzip -l rozha-one-v7-latin.zip > rozha-one-v7-latin-temp.txt
unzip -l rubik-mono-one-v8-latin.zip > rubik-mono-one-v8-latin-temp.txt
unzip -l rubik-v9-latin.zip > rubik-v9-latin-temp.txt
unzip -l ruda-v13-latin.zip > ruda-v13-latin-temp.txt
unzip -l rufina-v7-latin.zip > rufina-v7-latin-temp.txt
unzip -l ruge-boogie-v11-latin.zip > ruge-boogie-v11-latin-temp.txt
unzip -l ruluko-v8-latin.zip > ruluko-v8-latin-temp.txt
unzip -l rum-raisin-v8-latin.zip > rum-raisin-v8-latin-temp.txt
unzip -l ruslan-display-v11-latin.zip > ruslan-display-v11-latin-temp.txt
unzip -l russo-one-v8-latin.zip > russo-one-v8-latin-temp.txt
unzip -l ruthie-v11-latin.zip > ruthie-v11-latin-temp.txt
unzip -l rye-v8-latin.zip > rye-v8-latin-temp.txt
unzip -l sacramento-v7-latin.zip > sacramento-v7-latin-temp.txt
unzip -l sahitya-v5-latin.zip > sahitya-v5-latin-temp.txt
unzip -l sail-v11-latin.zip > sail-v11-latin-temp.txt
unzip -l saira-condensed-v5-latin.zip > saira-condensed-v5-latin-temp.txt
unzip -l saira-extra-condensed-v5-latin.zip > saira-extra-condensed-v5-latin-temp.txt
unzip -l saira-semi-condensed-v5-latin.zip > saira-semi-condensed-v5-latin-temp.txt
unzip -l saira-stencil-one-v2-latin.zip > saira-stencil-one-v2-latin-temp.txt
unzip -l saira-v4-latin.zip > saira-v4-latin-temp.txt
unzip -l salsa-v10-latin.zip > salsa-v10-latin-temp.txt
unzip -l sanchez-v7-latin.zip > sanchez-v7-latin-temp.txt
unzip -l sancreek-v11-latin.zip > sancreek-v11-latin-temp.txt
unzip -l sansita-v5-latin.zip > sansita-v5-latin-temp.txt
unzip -l sarabun-v7-latin.zip > sarabun-v7-latin-temp.txt
unzip -l sarala-v4-latin.zip > sarala-v4-latin-temp.txt
unzip -l sarina-v9-latin.zip > sarina-v9-latin-temp.txt
unzip -l sarpanch-v6-latin.zip > sarpanch-v6-latin-temp.txt
unzip -l satisfy-v10-latin.zip > satisfy-v10-latin-temp.txt
unzip -l sawarabi-gothic-v8-latin.zip > sawarabi-gothic-v8-latin-temp.txt
unzip -l sawarabi-mincho-v10-latin.zip > sawarabi-mincho-v10-latin-temp.txt
unzip -l scada-v8-latin.zip > scada-v8-latin-temp.txt
unzip -l scheherazade-v17-latin.zip > scheherazade-v17-latin-temp.txt
unzip -l schoolbell-v11-latin.zip > schoolbell-v11-latin-temp.txt
unzip -l scope-one-v7-latin.zip > scope-one-v7-latin-temp.txt
unzip -l seaweed-script-v7-latin.zip > seaweed-script-v7-latin-temp.txt
unzip -l secular-one-v5-latin.zip > secular-one-v5-latin-temp.txt
unzip -l sedgwick-ave-display-v6-latin.zip > sedgwick-ave-display-v6-latin-temp.txt
unzip -l sedgwick-ave-v6-latin.zip > sedgwick-ave-v6-latin-temp.txt
unzip -l sen-v2-latin.zip > sen-v2-latin-temp.txt
unzip -l sevillana-v9-latin.zip > sevillana-v9-latin-temp.txt
unzip -l seymour-one-v8-latin.zip > seymour-one-v8-latin-temp.txt
unzip -l shadows-into-light-two-v7-latin.zip > shadows-into-light-two-v7-latin-temp.txt
unzip -l shadows-into-light-v9-latin.zip > shadows-into-light-v9-latin-temp.txt
unzip -l shanti-v12-latin.zip > shanti-v12-latin-temp.txt
unzip -l share-tech-mono-v9-latin.zip > share-tech-mono-v9-latin-temp.txt
unzip -l share-tech-v10-latin.zip > share-tech-v10-latin-temp.txt
unzip -l share-v10-latin.zip > share-v10-latin-temp.txt
unzip -l shojumaru-v8-latin.zip > shojumaru-v8-latin-temp.txt
unzip -l short-stack-v10-latin.zip > short-stack-v10-latin-temp.txt
unzip -l shrikhand-v5-latin.zip > shrikhand-v5-latin-temp.txt
unzip -l sigmar-one-v10-latin.zip > sigmar-one-v10-latin-temp.txt
unzip -l signika-negative-v10-latin.zip > signika-negative-v10-latin-temp.txt
unzip -l signika-v11-latin.zip > signika-v11-latin-temp.txt
unzip -l simonetta-v11-latin.zip > simonetta-v11-latin-temp.txt
unzip -l sintony-v7-latin.zip > sintony-v7-latin-temp.txt
unzip -l sirin-stencil-v9-latin.zip > sirin-stencil-v9-latin-temp.txt
unzip -l six-caps-v10-latin.zip > six-caps-v10-latin-temp.txt
unzip -l skranji-v8-latin.zip > skranji-v8-latin-temp.txt
unzip -l slabo-13px-v8-latin.zip > slabo-13px-v8-latin-temp.txt
unzip -l slabo-27px-v6-latin.zip > slabo-27px-v6-latin-temp.txt
unzip -l slackey-v11-latin.zip > slackey-v11-latin-temp.txt
unzip -l smokum-v11-latin.zip > smokum-v11-latin-temp.txt
unzip -l smythe-v11-latin.zip > smythe-v11-latin-temp.txt
unzip -l sniglet-v12-latin.zip > sniglet-v12-latin-temp.txt
unzip -l snippet-v10-latin.zip > snippet-v10-latin-temp.txt
unzip -l snowburst-one-v8-latin.zip > snowburst-one-v8-latin-temp.txt
unzip -l sofadi-one-v9-latin.zip > sofadi-one-v9-latin-temp.txt
unzip -l sofia-v9-latin.zip > sofia-v9-latin-temp.txt
unzip -l solway-v3-latin.zip > solway-v3-latin-temp.txt
unzip -l song-myung-v8-latin.zip > song-myung-v8-latin-temp.txt
unzip -l sonsie-one-v9-latin.zip > sonsie-one-v9-latin-temp.txt
unzip -l sora-v1-latin.zip > sora-v1-latin-temp.txt
unzip -l sorts-mill-goudy-v9-latin.zip > sorts-mill-goudy-v9-latin-temp.txt
unzip -l source-code-pro-v11-latin.zip > source-code-pro-v11-latin-temp.txt
unzip -l source-sans-pro-v13-latin.zip > source-sans-pro-v13-latin-temp.txt
unzip -l source-serif-pro-v8-latin.zip > source-serif-pro-v8-latin-temp.txt
unzip -l space-mono-v5-latin.zip > space-mono-v5-latin-temp.txt
unzip -l spartan-v2-latin.zip > spartan-v2-latin-temp.txt
unzip -l special-elite-v10-latin.zip > special-elite-v10-latin-temp.txt
unzip -l spectral-sc-v5-latin.zip > spectral-sc-v5-latin-temp.txt
unzip -l spectral-v6-latin.zip > spectral-v6-latin-temp.txt
unzip -l spicy-rice-v9-latin.zip > spicy-rice-v9-latin-temp.txt
unzip -l spinnaker-v11-latin.zip > spinnaker-v11-latin-temp.txt
unzip -l spirax-v9-latin.zip > spirax-v9-latin-temp.txt
unzip -l squada-one-v8-latin.zip > squada-one-v8-latin-temp.txt
unzip -l sree-krushnadevaraya-v8-latin.zip > sree-krushnadevaraya-v8-latin-temp.txt
unzip -l sriracha-v4-latin.zip > sriracha-v4-latin-temp.txt
unzip -l srisakdi-v4-latin.zip > srisakdi-v4-latin-temp.txt
unzip -l staatliches-v3-latin.zip > staatliches-v3-latin-temp.txt
unzip -l stalemate-v8-latin.zip > stalemate-v8-latin-temp.txt
unzip -l stalinist-one-v26-latin.zip > stalinist-one-v26-latin-temp.txt
unzip -l stardos-stencil-v11-latin.zip > stardos-stencil-v11-latin-temp.txt
unzip -l stint-ultra-condensed-v9-latin.zip > stint-ultra-condensed-v9-latin-temp.txt
unzip -l stint-ultra-expanded-v8-latin.zip > stint-ultra-expanded-v8-latin-temp.txt
unzip -l stoke-v10-latin.zip > stoke-v10-latin-temp.txt
unzip -l strait-v8-latin.zip > strait-v8-latin-temp.txt
unzip -l stylish-v8-latin.zip > stylish-v8-latin-temp.txt
unzip -l sue-ellen-francisco-v11-latin.zip > sue-ellen-francisco-v11-latin-temp.txt
unzip -l suez-one-v4-latin.zip > suez-one-v4-latin-temp.txt
unzip -l sulphur-point-v2-latin.zip > sulphur-point-v2-latin-temp.txt
unzip -l sumana-v5-latin.zip > sumana-v5-latin-temp.txt
unzip -l sunflower-v9-latin.zip > sunflower-v9-latin-temp.txt
unzip -l sunshiney-v11-latin.zip > sunshiney-v11-latin-temp.txt
unzip -l supermercado-one-v10-latin.zip > supermercado-one-v10-latin-temp.txt
unzip -l suranna-v7-latin.zip > suranna-v7-latin-temp.txt
unzip -l sura-v5-latin.zip > sura-v5-latin-temp.txt
unzip -l suravaram-v7-latin.zip > suravaram-v7-latin-temp.txt
unzip -l swanky-and-moo-moo-v10-latin.zip > swanky-and-moo-moo-v10-latin-temp.txt
unzip -l syncopate-v11-latin.zip > syncopate-v11-latin-temp.txt
unzip -l tajawal-v3-latin.zip > tajawal-v3-latin-temp.txt
unzip -l tangerine-v11-latin.zip > tangerine-v11-latin-temp.txt
unzip -l tauri-v9-latin.zip > tauri-v9-latin-temp.txt
unzip -l taviraj-v5-latin.zip > taviraj-v5-latin-temp.txt
unzip -l teko-v9-latin.zip > teko-v9-latin-temp.txt
unzip -l telex-v8-latin.zip > telex-v8-latin-temp.txt
unzip -l tenali-ramakrishna-v7-latin.zip > tenali-ramakrishna-v7-latin-temp.txt
unzip -l tenor-sans-v11-latin.zip > tenor-sans-v11-latin-temp.txt
unzip -l text-me-one-v8-latin.zip > text-me-one-v8-latin-temp.txt
unzip -l thasadith-v4-latin.zip > thasadith-v4-latin-temp.txt
unzip -l the-girl-next-door-v11-latin.zip > the-girl-next-door-v11-latin-temp.txt
unzip -l tienne-v13-latin.zip > tienne-v13-latin-temp.txt
unzip -l tillana-v6-latin.zip > tillana-v6-latin-temp.txt
unzip -l timmana-v5-latin.zip > timmana-v5-latin-temp.txt
unzip -l tinos-v13-latin.zip > tinos-v13-latin-temp.txt
unzip -l titan-one-v8-latin.zip > titan-one-v8-latin-temp.txt
unzip -l titillium-web-v8-latin.zip > titillium-web-v8-latin-temp.txt
unzip -l tomorrow-v3-latin.zip > tomorrow-v3-latin-temp.txt
unzip -l trade-winds-v9-latin.zip > trade-winds-v9-latin-temp.txt
unzip -l trirong-v5-latin.zip > trirong-v5-latin-temp.txt
unzip -l trocchi-v9-latin.zip > trocchi-v9-latin-temp.txt
unzip -l trochut-v8-latin.zip > trochut-v8-latin-temp.txt
unzip -l trykker-v9-latin.zip > trykker-v9-latin-temp.txt
unzip -l tulpen-one-v10-latin.zip > tulpen-one-v10-latin-temp.txt
unzip -l turret-road-v2-latin.zip > turret-road-v2-latin-temp.txt
unzip -l ubuntu-condensed-v10-latin.zip > ubuntu-condensed-v10-latin-temp.txt
unzip -l ubuntu-mono-v9-latin.zip > ubuntu-mono-v9-latin-temp.txt
unzip -l ubuntu-v14-latin.zip > ubuntu-v14-latin-temp.txt
unzip -l ultra-v12-latin.zip > ultra-v12-latin-temp.txt
unzip -l uncial-antiqua-v8-latin.zip > uncial-antiqua-v8-latin-temp.txt
unzip -l underdog-v9-latin.zip > underdog-v9-latin-temp.txt
unzip -l unica-one-v7-latin.zip > unica-one-v7-latin-temp.txt
unzip -l unifrakturcook-v12-latin.zip > unifrakturcook-v12-latin-temp.txt
unzip -l unifrakturmaguntia-v11-latin.zip > unifrakturmaguntia-v11-latin-temp.txt
unzip -l unkempt-v12-latin.zip > unkempt-v12-latin-temp.txt
unzip -l unlock-v10-latin.zip > unlock-v10-latin-temp.txt
unzip -l unna-v13-latin.zip > unna-v13-latin-temp.txt
unzip -l vampiro-one-v11-latin.zip > vampiro-one-v11-latin-temp.txt
unzip -l varela-round-v12-latin.zip > varela-round-v12-latin-temp.txt
unzip -l varela-v10-latin.zip > varela-v10-latin-temp.txt
unzip -l varta-v1-latin.zip > varta-v1-latin-temp.txt
unzip -l vast-shadow-v10-latin.zip > vast-shadow-v10-latin-temp.txt
unzip -l vesper-libre-v12-latin.zip > vesper-libre-v12-latin-temp.txt
unzip -l viaoda-libre-v3-latin.zip > viaoda-libre-v3-latin-temp.txt
unzip -l vibes-v2-latin.zip > vibes-v2-latin-temp.txt
unzip -l vibur-v11-latin.zip > vibur-v11-latin-temp.txt
unzip -l vidaloka-v12-latin.zip > vidaloka-v12-latin-temp.txt
unzip -l viga-v8-latin.zip > viga-v8-latin-temp.txt
unzip -l voces-v10-latin.zip > voces-v10-latin-temp.txt
unzip -l volkhov-v11-latin.zip > volkhov-v11-latin-temp.txt
unzip -l vollkorn-sc-v4-latin.zip > vollkorn-sc-v4-latin-temp.txt
unzip -l vollkorn-v12-latin.zip > vollkorn-v12-latin-temp.txt
unzip -l voltaire-v10-latin.zip > voltaire-v10-latin-temp.txt
unzip -l vt323-v11-latin.zip > vt323-v11-latin-temp.txt
unzip -l waiting-for-the-sunrise-v11-latin.zip > waiting-for-the-sunrise-v11-latin-temp.txt
unzip -l wallpoet-v12-latin.zip > wallpoet-v12-latin-temp.txt
unzip -l walter-turncoat-v11-latin.zip > walter-turncoat-v11-latin-temp.txt
unzip -l warnes-v10-latin.zip > warnes-v10-latin-temp.txt
unzip -l wellfleet-v8-latin.zip > wellfleet-v8-latin-temp.txt
unzip -l wendy-one-v9-latin.zip > wendy-one-v9-latin-temp.txt
unzip -l wire-one-v11-latin.zip > wire-one-v11-latin-temp.txt
unzip -l work-sans-v8-latin.zip > work-sans-v8-latin-temp.txt
unzip -l yanone-kaffeesatz-v15-latin.zip > yanone-kaffeesatz-v15-latin-temp.txt
unzip -l yantramanav-v5-latin.zip > yantramanav-v5-latin-temp.txt
unzip -l yatra-one-v7-latin.zip > yatra-one-v7-latin-temp.txt
unzip -l yellowtail-v10-latin.zip > yellowtail-v10-latin-temp.txt
unzip -l yeon-sung-v8-latin.zip > yeon-sung-v8-latin-temp.txt
unzip -l yeseva-one-v14-latin.zip > yeseva-one-v14-latin-temp.txt
unzip -l yesteryear-v8-latin.zip > yesteryear-v8-latin-temp.txt
unzip -l yrsa-v5-latin.zip > yrsa-v5-latin-temp.txt
unzip -l zcool-kuaile-v5-latin.zip > zcool-kuaile-v5-latin-temp.txt
unzip -l zcool-qingke-huangyou-v5-latin.zip > zcool-qingke-huangyou-v5-latin-temp.txt
unzip -l zcool-xiaowei-v5-latin.zip > zcool-xiaowei-v5-latin-temp.txt
unzip -l zeyada-v10-latin.zip > zeyada-v10-latin-temp.txt
unzip -l zhi-mang-xing-v5-latin.zip > zhi-mang-xing-v5-latin-temp.txt
unzip -l zilla-slab-highlight-v8-latin.zip > zilla-slab-highlight-v8-latin-temp.txt
unzip -l zilla-slab-v5-latin.zip > zilla-slab-v5-latin-temp.txt

type *-temp.txt > _a.txt
pause